### PR TITLE
elegant object badges

### PR DESCRIPTION
**Pull request by ashtonhogan**
Added new elegant object badges with their respective icons

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#39](https://github.com/yegor256/elegantobjects.github.io/issues/39) is now in scope, role is `REV`

**Comment by filfreire** [comment]
@ashtonhogan you could add a screenshot of the badges in the PR description to get an idea of how they look.

**Comment by ashtonhogan** [comment]
@filfreire 

download
download 5
download 4
download 3
download 2
download 1

**Comment by 0crat** [comment]
The job [#39](https://github.com/yegor256/elegantobjects.github.io/issues/39) is now out of scope

**Pull request closed without merging**
