### PR TITLE
Add new framework Page and cutie as a base for this framework

### PR DESCRIPTION
**Pull request by Guseyn**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@Guseyn this pull request is too small, just 4 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@Guseyn there are merge conflicts, please rebase

**Comment by Guseyn** [comment]
@yegor256 Done.

**Comment by yegor256** [comment]
@Guseyn thanks!

**Comment by 0crat** [comment]
This job is not in scope

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#74` is not assigned, can't get performer

**Pull request merged**
