### PR TITLE
Added CryptoCactoos

### PR DESCRIPTION
**Pull request by g4s8**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by yegor256** [comment]
@g4s8 I believe the url has changed to https://github.com/g4s8/cactoos-crypto Please, update

**Comment by g4s8** [comment]
@yegor256 updated

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
