### PR TITLE
add Tacinga to EO frameworks/libraries

### PR DESCRIPTION
**Pull request by ashtonhogan**
Adding my [testing framework](https://github.com/ashtonhogan/tacinga), as an alternative to JUnit and TestNG but using Elegant Objects principles.

The name "Tacinga" is taken from the cactus family.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#24](https://github.com/yegor256/elegantobjects.github.io/issues/24) is now in scope, role is `REV`

**Comment by ashtonhogan** [comment]
bump

**Comment by ashtonhogan** [comment]
@yegor256 Can you check now, it's come a long way, I believe it's ready

**Comment by ashtonhogan** [comment]
22 days and counting... doesn't seem to be that difficult to merge. Have I missed a step somewhere? If things take this long now, I can't imagine if there are 500 projects. Feel free to add me as a collaborator to this repo @yegor256 @0crat

**Comment by 0crat** [comment]
Are you speaking to me or about me [here](https://github.com/yegor256/elegantobjects.github.io/issues/24#issuecomment-371457397); you must always start your message with my name if you want to address it to me, see [§1](http://www.zerocracy.com/policy.html#1)

**Comment by 0crat** [comment]
The job [#24](https://github.com/yegor256/elegantobjects.github.io/issues/24) is now out of scope

**Pull request closed without merging**
