### PR TITLE
Added @smallcreep as fan

### PR DESCRIPTION
**Pull request by smallcreep**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
I can't do it for technical reasons, I'm very sorry. If you don't know what to do, submit this error as a ticket [here](https://github.com/zerocracy/datum):

```
1.0-SNAPSHOT e8fd8525 2018-01-08T11:53:03
IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/scope/wbs/add_job_to_wbs.groovy
java.lang.IllegalStateException: java.lang.reflect.InvocationTargetException in com/zerocracy/stk/pm/scope/wbs/add_job_to_wbs.groovy
	at com.zerocracy.farm.reactive.StkGroovy.process(StkGroovy.java:125)
	at com.zerocracy.farm.StkSafe.process(StkSafe.java:87)
	at com.zerocracy.farm.reactive.StkSmart.process(StkSmart.java:66)
	at com.zerocracy.farm.reactive.Brigade.process(Brigade.java:82)
	at com.zerocracy.farm.reactive.Brigade.lambda$apply$0(Brigade.java:64)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
	at org.cactoos.func.IoCheckedBiFunc.apply(IoCheckedBiFunc.java:66)
	at org.cactoos.func.UncheckedBiFunc.apply(UncheckedBiFunc.java:60)
	at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
	at org.cactoos.iterator.Filtered.hasNext(Filtered.java:90)
	at org.cactoos.iterator.LengthOf.lambda$new$0(LengthOf.java:52)
	at org.cactoos.scalar.UncheckedScalar.lambda$value$0(UncheckedScalar.java:58)
	at org.cactoos.func.UncheckedFunc.lambda$apply$0(Uncheck...
```

Cc @yegor256

**Comment by yegor256** [comment]
@smallcreep thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/elegantobjects.github.io#17` is not assigned, can't get start time

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/elegantobjects.github.io#17` was not in scope

**Pull request merged**
