### PR TITLE
Add laconic-velocity to EO libs

### PR DESCRIPTION
**Pull request by dgroup**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@dgroup[/z](https://www.0crat.com/u/dgroup) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by dgroup** [comment]
Hi @yegor256,
Please review the this PR.

**Comment by dgroup** [comment]
@yegor256, up.

**Comment by yegor256** [comment]
@dgroup thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#68` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
