### PR TITLE
 Added some links and a fun.

### PR DESCRIPTION
**Pull request by alex-semenyuk**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by yegor256** [comment]
@alex-semenyuk thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/elegantobjects.github.io#15` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#15` is now out of scope.

**Pull request merged**
