### PR TITLE
matchers-json

### PR DESCRIPTION
**Pull request by g4s8**
Added [matchers-json](https://github.com/g4s8/matchers-json): hamcrest matchers for [single statement unit testing](https://www.yegor256.com/2017/05/17/single-statement-unit-tests.html) with JSON objects.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@g4s8[/z](https://www.0crat.com/u/g4s8) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@g4s8 conflicts :( Please, fix and I'll merge

**Comment by g4s8** [comment]
@yegor256 done

**Comment by yegor256** [comment]
@g4s8 thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#66` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
