### PR TITLE
add fan @gennadygennady

### PR DESCRIPTION
**Pull request by gennadygennady**
Organized <a> tags with indentation based on the starting letter for improved readability

### CODE REVIEW

**Comment by yegor256** [comment]
@gennadygennady better keep the formatting as is

**Comment by gennadygennady** [comment]
@yegor256 ok, i will rollback it. But why?

**Comment by horw** [comment]
I also found that this formatting should be updated; these tabs are inconsistent now

**Comment by horw** [comment]
> @yegor256 ok, i will rollback it. But why?

+1 I also found that this formatting should be updated; these tabs are inconsistent now

**Pull request merged**
