### PR TITLE
added principle for DI

### PR DESCRIPTION
**Pull request by ashtonhogan**
@yegor256 I wasn't entirely sure about this one. Your article mentions `DI containers` in particular, not really `DI` in general. I'm still uncertain which side of the fence you're on with that...

I don't see it listed anywhere [here](http://www.yegor256.com/2016/02/03/design-patterns-and-anti-patterns.html) either

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#26](https://github.com/yegor256/elegantobjects.github.io/issues/26) is now in scope, role is `REV`

**Comment by ashtonhogan** [comment]
@yegor256 I wasn't entirely sure about this one. Your article mentions `DI containers` in particular, not really `DI` in general. I'm still uncertain which side of the fence you're on with that...

I don't see it listed anywhere [here](http://www.yegor256.com/2016/02/03/design-patterns-and-anti-patterns.html) either

**Comment by ashtonhogan** [comment]
bump

**Comment by yegor256** [comment]
@ashtonhogan we are against DI containers, not DI by itself

**Comment by ashtonhogan** [comment]
@yegor256 why? DI is a Martin Fowler thing, I have my doubts. Can you reference any OOP experts saying DI is good?

**Comment by yegor256** [comment]
@ashtonhogan you can find more information here: http://www.yegor256.com/2014/10/03/di-containers-are-evil.html

**Comment by ashtonhogan** [comment]
@yegor256 I've read that article about 30 times. I even posted a reply on how people can get away from DI containers like Spring. That article says nothing about David West, Alan Kay, etc nominating DI for good OOP practice

**Comment by ashtonhogan** [comment]
@yegor256 What about this as a principle: "Object Composition instead of Dependency Injection"?

**Comment by ashtonhogan** [comment]
@yegor256 What about this as a principle: "Object Composition instead of Dependency Injection"?

It seems that object composition would historically refer to encapsulation as a whole until DI came along and hijacked parts of it. Now when you say "Composition" people think:

```
new Foo(FooBar fooBar){
    this.bar = new Bar(fooBar);
}
```

And when you say "Dependency Injection" people think:

```
new Foo(Bar bar){
   this.bar = bar;
}
```

**Comment by 0crat** [comment]
The job [#26](https://github.com/yegor256/elegantobjects.github.io/issues/26) is now out of scope

**Pull request closed without merging**
