### PR TITLE
Add Kactoos, Kotlin port of Cactoos

### PR DESCRIPTION
**Pull request by filfreire**
/cc @yegor256

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#20](https://github.com/yegor256/elegantobjects.github.io/issues/20) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@filfreire thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#20` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#20](https://github.com/yegor256/elegantobjects.github.io/issues/20) is now out of scope

**Pull request merged**
