### PR TITLE
Added xls library to the list

### PR DESCRIPTION
**Pull request by Vatavuk**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#19](https://github.com/yegor256/elegantobjects.github.io/issues/19) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@Vatavuk thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#19` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#19](https://github.com/yegor256/elegantobjects.github.io/issues/19) is now out of scope

**Pull request merged**
