### PR TITLE
Added @aliceice to fans

### PR DESCRIPTION
**Pull request by aliceice**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](http://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job gh:yegor256/elegantobjects.github.io#18 is now in scope, role is `REV`

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#18` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job gh:yegor256/elegantobjects.github.io#18 is now out of scope

**Comment by yegor256** [comment]
@aliceice thanks!

**Pull request merged**
