### PR TITLE
Introducing Puzzler-bot

### PR DESCRIPTION
**Pull request by skapral**
Hi @yegor256.

Let me introduce my new tool for managing puzzles - [@puzzlerbot](https://github.com/skapral/puzzlerbot). It is supposed to work either alone or in pair with [0pdd](https://github.com/yegor256/0pdd/). It's aim is to provide new ways of organizing PDD approach in GitHub.

Hope it would be helpful for our EO community.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@skapral thanks

**Comment by 0crat** [comment]
The job is not in WBS, won't close the order

**Pull request merged**
