### PR TITLE
add t-izbassar to fans

### PR DESCRIPTION
**Pull request by t-izbassar**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#25](https://github.com/yegor256/elegantobjects.github.io/issues/25) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@t-izbassar thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#25` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#25](https://github.com/yegor256/elegantobjects.github.io/issues/25) is now out of scope

**Pull request merged**
