### PR TITLE
Added more resources

### PR DESCRIPTION
**Pull request by amihaiemil**
Added 2 of my articles, which I think best describe the advantages of EO-style + a few libraries and a project.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#49](https://github.com/yegor256/elegantobjects.github.io/issues/49) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` are banned at this job; I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@amihaiemil thanks!

**Comment by 0crat** [comment]
The job [#49](https://github.com/yegor256/elegantobjects.github.io/issues/49) is now out of scope

**Pull request merged**
