### PR TITLE
Add @koeeenig to list of fans

### PR DESCRIPTION
**Pull request by koeeenig**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this pull request

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#16` is now in scope.

**Comment by yegor256** [comment]
@koeeenig thanks!

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/elegantobjects.github.io#16` is not assigned, can't get start time

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#16` is now out of scope.

**Pull request merged**
