### PR TITLE
Updated references to project-avral products after rebranding.

### PR DESCRIPTION
**Pull request by skapral**
Recently I did a big reorganization inside @project-avral and its projects. Now it is named @pragmatic-objects.

- Changed the name of my GitHub organization from project-avral to pragmatic-objects.
- Also, OO-Atom was splat to two products - OO-Atom and OO-Tests. Reflected that too.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@skapral[/z](https://www.0crat.com/u/skapral) this pull request is too small, just 6 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by yegor256** [comment]
@skapral oops, conflicts :( Please fix them and I'll merge

**Comment by skapral** [comment]
@yegor256 done

**Comment by yegor256** [comment]
@skapral thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#63` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
