### PR TITLE
Add Xive, a EO conform data storage layer

### PR DESCRIPTION
**Pull request by Meerownymous**
We currently rewrite a rather complex project of ours. We started from scratch and with EO principles and work with them for over a year now.

In search of solutions for a whole app, we studied Zerocracy and kind of extracted a storage layer which enables us to build our entities in the form of „xml speaking objects“ from it.

We made it threadsafe, cacheable and added some flexibility so that it suits our needs.

Its open source, we would like to present it on your page.

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@Meerownymous this pull request is too small, just 2 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by Meerownymous** [comment]
@yegor256 I updated the description. What do you think? Not OO enough for your page? :)

**Comment by yegor256** [comment]
@Meerownymous looks great, but there are merge conflicts, please rebase and I will merge

**Comment by Meerownymous** [comment]
@yegor256 done

**Comment by yegor256** [comment]
@Meerownymous thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#73` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope

**Pull request merged**
