### PR TITLE
Add one more fan

### PR DESCRIPTION
**Pull request by proshin-roman**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#22](https://github.com/yegor256/elegantobjects.github.io/issues/22) is now in scope, role is `REV`

**Comment by yegor256** [comment]
@proshin-roman thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/elegantobjects.github.io#22` is not assigned, can't get start time

**Comment by 0crat** [comment]
The job [#22](https://github.com/yegor256/elegantobjects.github.io/issues/22) is now out of scope

**Pull request merged**
