### PR TITLE
Add one user and one repo

### PR DESCRIPTION
**Pull request by mgramin**

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
@mgramin[/z](https://www.0crat.com/u/mgramin) this pull request is too small, just 3 lines changed (less than 10), there will be no formal code review; in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by mgramin** [comment]
@yegor256 thanks for your questions.

I use getters/setters only to interact with third-party libraries (e.g. swagger and spring-boot magic)
(In the future i plan to get rid of the spring boot).

All application are based on simple interfaces with simple implementations and many many decorators.

For example:

Interface - com.github.mgramin.sqlboot.model.resource_type.ResourceType

Its implementations:
- com.github.mgramin.sqlboot.model.resource_type.impl.sql.SqlResourceType
- com.github.mgramin.sqlboot.model.resource_type.impl.FakeDbResourceType
- com.github.mgramin.sqlboot.model.resource_type.impl.file.FileResourceType
- com.github.mgramin.sqlboot.model.resource_type.impl.composite.FsResourceTypes
- etc

Its decorators:
- com.github.mgramin.sqlboot.model.resource_type.wrappers.header.SelectWrapper
- com.github.mgramin.sqlboot.model.resource_type.wrappers.list.CacheWrapper
- com.github.mgramin.sqlboot.model.resource_type.wrappers.list.DistinctWrapper
- com.github.mgramin.sqlboot.model.resource_type.wrappers.list.LimitWrapper
- com.github.mgramin.sqlboot.model.resource_type.wrappers.list.OrderByWrapper
- com.github.mgramin.sqlboot.model.resource_type.wrappers.list.PageWrapper
- com.github.mgramin.sqlboot.model.resource_type.wrappers.list.WhereWrapper
- com.github.mgramin.sqlboot.model.resource_type.wrappers.body.TemplateBodyWrapper
- com.github.mgramin.sqlboot.model.resource_type.wrappers.body.SqlBodyWrapper
- etc

All these classes are pure immutability.

A more detailed analysis of my project was made in the @amihaiemil review for the Software Quality Award 2017 -  https://gist.github.com/amihaiemil/239169ef959fc064307e06aef6d30fd4

**Comment by yegor256** [comment]
@mgramin thanks!

**Pull request merged**
