### PR TITLE
Add myself to fans list

### PR DESCRIPTION
**Pull request by baudoliver7**
I love this approach and principles of Elegant Objects. I'm pleased to be part of fans list. :)

### CODE REVIEW

**Comment by baudoliver7** [comment]
@yegor256 Please check/merge.

**Comment by 0crat** [comment]
@baudoliver7[/z](https://www.0crat.com/u/baudoliver7) this pull request is too small, just 1 lines changed (less than 10), there will be no formal code review, see [§53](http://www.zerocracy.com/policy.html#53) and [§28](http://www.zerocracy.com/policy.html#28); in the future, try to make sure your pull requests are not too small; @yegor256[/z](https://www.0crat.com/u/yegor256) please review this and merge or reject

**Comment by baudoliver7** [comment]
@yegor256 ping

**Comment by yegor256** [comment]
@baudoliver7 thanks!

**Pull request merged**
